In [1]:
import pandas as pd 

PATH = "COVID-19-master/csse_covid_19_data/csse_covid_19_daily_reports/"
doc = pd.read_csv(f"{PATH}04-01-2020.csv", encoding="utf-8-sig")
doc.head()

,FIPS,Admin2,Province_State,Country_Region,Last_Update,Lat,Long_,Confirmed,Deaths,Recovered,Active,Combined_Key
0,45001.0,Abbeville,South Carolina,US,2020-04-01 21:58:49,34.223334,-82.461707,4,0,0,4,"Abbeville, South Carolina, US"
1,22001.0,Acadia,Louisiana,US,2020-04-01 21:58:49,30.295065,-92.414197,47,1,0,46,"Acadia, Louisiana, US"
2,51001.0,Accomack,Virginia,US,2020-04-01 21:58:49,37.767072,-75.632346,7,0,0,7,"Accomack, Virginia, US"
3,16001.0,Ada,Idaho,US,2020-04-01 21:58:49,43.452658,-116.241552,195,3,0,192,"Ada, Idaho, US"
4,19001.0,Adair,Iowa,US,2020-04-01 21:58:49,41.330756,-94.471059,1,0,0,1,"Adair, Iowa, US"

In [2]:
import pandas as pd 

PATH = "COVID-19-master/csse_covid_19_data/csse_covid_19_daily_reports/"
doc = pd.read_csv(f"{PATH}03-01-2020.csv", encoding="utf-8-sig")
doc.head()

,Province/State,Country/Region,Last Update,Confirmed,Deaths,Recovered,Latitude,Longitude
0,Hubei,Mainland China,2020-03-01T10:13:19,66907,2761,31536,30.9756,112.2707
1,NaN,South Korea,2020-03-01T23:43:03,3736,17,30,36.0000,128.0000
2,NaN,Italy,2020-03-01T23:23:02,1694,34,83,43.0000,12.0000
3,Guangdong,Mainland China,2020-03-01T14:13:18,1349,7,1016,23.3417,113.4244
4,Henan,Mainland China,2020-03-01T14:13:18,1272,22,1198,33.8820,113.6140

In [4]:
doc = pd.read_csv(f"{PATH}01-22-2020.csv", encoding="utf-8-sig")
doc

,Province/State,Country/Region,Last Update,Confirmed,Deaths,Recovered
0,Anhui,Mainland China,1/22/2020 17:00,1.0,NaN,NaN
1,Beijing,Mainland China,1/22/2020 17:00,14.0,NaN,NaN
2,Chongqing,Mainland China,1/22/2020 17:00,6.0,NaN,NaN
3,Fujian,Mainland China,1/22/2020 17:00,1.0,NaN,NaN
4,Gansu,Mainland China,1/22/2020 17:00,NaN,NaN,NaN
...,...,...,...,...,...,...
71,Unknown,United Kingdom,1/22/2020 17:00,0.0,0.0,0.0
72,NaN,Nauru,1/22/2020 17:00,0.0,0.0,0.0
73,Niue,New Zealand,1/22/2020 17:00,0.0,0.0,0.0
74,NaN,Tuvalu,1/22/2020 17:00,0.0,0.0,0.0
75,Pitcairn Islands,United Kingdom,1/22/2020 17:00,0.0,0.0,0.0

In [6]:
doc = pd.read_csv(f"{PATH}01-22-2020.csv", encoding="utf-8-sig")

try :
    doc = doc[["Province_State", "Country_Region","Confirmed"]]

except :
    doc = doc[["Province/State", "Country/Region","Confirmed"]]
    doc.columns = ["Province_State","Country_Region", "Confirmed"]

doc.head()

  Province_State  Country_Region  Confirmed
0          Anhui  Mainland China        1.0
1        Beijing  Mainland China       14.0
2      Chongqing  Mainland China        6.0
3         Fujian  Mainland China        1.0
4          Gansu  Mainland China        NaN

In [7]:
doc = pd.read_csv(f"{PATH}03-01-2020.csv", encoding="utf-8-sig")

try :
    doc = doc[["Province_State", "Country_Region","Confirmed"]]

except :
    doc = doc[["Province/State", "Country/Region","Confirmed"]]
    doc.columns = ["Province_State","Country_Region", "Confirmed"]

doc.head()

  Province_State  Country_Region  Confirmed
0          Hubei  Mainland China      66907
1            NaN     South Korea       3736
2            NaN           Italy       1694
3      Guangdong  Mainland China       1349
4          Henan  Mainland China       1272

In [8]:
#필드명 및 컬럼 타입 변경 

doc = pd.read_csv(f"{PATH}01-22-2020.csv", encoding="utf-8-sig")

try :
    doc = doc[["Province_State", "Country_Region","Confirmed"]]

except :
    doc = doc[["Province/State", "Country/Region","Confirmed"]]
    doc.columns = ["Province_State","Country_Region", "Confirmed"]

doc = doc.dropna(subset=["Confirmed"])
doc = doc.astype({"Confirmed" : "int64"})
doc.head()

  Province_State  Country_Region  Confirmed
0          Anhui  Mainland China          1
1        Beijing  Mainland China         14
2      Chongqing  Mainland China          6
3         Fujian  Mainland China          1
5      Guangdong  Mainland China         26

In [10]:
#국기 정보 가져오기

country_info = pd.read_csv("COVID-19-master/csse_covid_19_data/UID_ISO_FIPS_LookUp_Table.csv", encoding="utf-8-sig")
country_info

,Unnamed: 0.1,Unnamed: 0,UID,iso2,iso3,code3,FIPS,Admin2,Province_State,Country_Region,Lat,Long_,Combined_Key
0,0,0,NaN,BW,NaN,NaN,NaN,NaN,NaN,Botswana,NaN,NaN,Botswana
1,1,1,NaN,BI,NaN,NaN,NaN,NaN,NaN,Burundi,NaN,NaN,Burundi
2,2,2,NaN,SL,NaN,NaN,NaN,NaN,NaN,Sierra Leone,NaN,NaN,Sierra Leone
3,3,3,4.0,AF,AFG,4.0,NaN,NaN,NaN,Afghanistan,33.939110,67.709953,Afghanistan
4,4,4,8.0,AL,ALB,8.0,NaN,NaN,NaN,Albania,41.153300,20.168300,Albania
...,...,...,...,...,...,...,...,...,...,...,...,...,...
3555,3555,3555,84056037.0,US,USA,840.0,56037.0,Sweetwater,Wyoming,US,41.659439,-108.882788,"Sweetwater, Wyoming, US"
3556,3556,3556,84056039.0,US,USA,840.0,56039.0,Teton,Wyoming,US,43.935225,-110.589080,"Teton, Wyoming, US"
3557,3557,3557,84056041.0,US,USA,840.0,56041.0,Uinta,Wyoming,US,41.287818,-110.547578,"Uinta, Wyoming, US"
3558,3558,3558,84056043.0,US,USA,840.0,56043.0,Washakie,Wyoming,US,43.904516,-107.680187,"Washakie, Wyoming, US"
3559,3559,3559,84056045.0,US,USA,840.0,56045.0,Weston,Wyoming,US,43.839612,-104.567488,"Weston, Wyoming, US"

In [13]:
test_df = pd.merge(doc, country_info, on="Country_Region", how="left")
test_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 3442 entries, 0 to 3441
Data columns (total 15 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   Province_State_x  3430 non-null   object
 1   Country_Region    3442 non-null   object
 2   Confirmed         3442 non-null   int64
 3   Unnamed: 0.1      3408 non-null   float64
 4   Unnamed: 0        3408 non-null   float64
 5   UID               3408 non-null   float64
 6   iso2              3408 non-null   object
 7   iso3              3408 non-null   object
 8   code3             3408 non-null   float64
 9   FIPS              3302 non-null   float64
 10  Admin2            3246 non-null   object
 11  Province_State_y  3377 non-null   object
 12  Lat               3303 non-null   float64
 13  Long_             3303 non-null   float64
 14  Combined_Key      3408 non-null   object
dtypes: float64(7), int64(1), object(7)
memory usage: 403.5+ KB

In [15]:
test_df.isnull().sum()

Province_State_x     12
Country_Region        0
Confirmed             0
Unnamed: 0.1         34
Unnamed: 0           34
UID                  34
iso2                 34
iso3                 34
code3                34
FIPS                140
Admin2              196
Province_State_y     65
Lat                 139
Long_               139
Combined_Key         34
dtype: int64

In [18]:
nan_rows = test_df[test_df["iso2"].isnull()]
nan_rows.head()

,Province_State_x,Country_Region,Confirmed,Unnamed: 0.1,Unnamed: 0,UID,iso2,iso3,code3,FIPS,Admin2,Province_State_y,Lat,Long_,Combined_Key
0,Anhui,Mainland China,1,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,Beijing,Mainland China,14,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,Chongqing,Mainland China,6,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,Fujian,Mainland China,1,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,Guangdong,Mainland China,26,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [20]:
import json 

with open ("COVID-19-master/csse_covid_19_data/country_convert.json", "r", encoding="utf-8-sig")as json_file : 
        json_data = json.load(json_file)
        print(json_data.keys())

dict_keys(['Mainland China', 'Macau', 'South Korea', 'Aruba', ' Azerbaijan', 'Bahamas, The', 'Cape Verde', 'Cayman Islands', 'Channel Islands', 'Curacao', 'Czech Republic', 'East Timor', 'Faroe Islands', 'French Guiana', 'Gambia, The', 'Gibraltar', 'Greenland', 'Guadeloupe', 'Guam', 'Guernsey', 'Hong Kong', 'Hong Kong SAR', 'Iran (Islamic Republic of)', 'Ivory Coast', 'Jersey', 'Macao SAR', 'Martinique', 'Mayotte', 'North Ireland', 'Palestine', 'Puerto Rico', 'Republic of Ireland', 'Republic of Korea', 'Republic of Moldova', 'Republic of the Congo', 'Reunion', 'Russian Federation', 'Saint Barthelemy', 'Saint Martin', 'St. Martin', 'Taipei and environs', 'The Bahamas', 'The Gambia', 'UK', 'Vatican City', 'Viet Nam', 'occupied Palestinian territory', 'Taiwan*', 'Malawi', 'South Sudan', 'Western Sahara', 'Namibia'])

In [22]:
df = pd.DataFrame({
    "영어" : [60,70],
    "수학" : [100,50],
    
    
},columns=["영어", "수학"], index=["Wonsil", "Dave"])

df

        영어   수학
Wonsil  60  100
Dave    70   50

In [29]:
# def func(df_data) :
#     print(type(df_data)),
#     print(df_data.index),
#     print(df_data.values),
#     return df_data
def func(df_data) :
    df_data["영어"] = 80
    return df_data

In [31]:
df_func = df.apply(func, axis=0)

In [32]:
df_func = df.apply(func, axis=1)

In [33]:
df_func

        영어   수학
Wonsil  80  100
Dave    80   50

In [34]:
import json 

with open ("COVID-19-master/csse_covid_19_data/country_convert.json", "r", encoding="utf-8-sig")as json_file : 
        json_data = json.load(json_file)
        print(json_data.keys())

dict_keys(['Mainland China', 'Macau', 'South Korea', 'Aruba', ' Azerbaijan', 'Bahamas, The', 'Cape Verde', 'Cayman Islands', 'Channel Islands', 'Curacao', 'Czech Republic', 'East Timor', 'Faroe Islands', 'French Guiana', 'Gambia, The', 'Gibraltar', 'Greenland', 'Guadeloupe', 'Guam', 'Guernsey', 'Hong Kong', 'Hong Kong SAR', 'Iran (Islamic Republic of)', 'Ivory Coast', 'Jersey', 'Macao SAR', 'Martinique', 'Mayotte', 'North Ireland', 'Palestine', 'Puerto Rico', 'Republic of Ireland', 'Republic of Korea', 'Republic of Moldova', 'Republic of the Congo', 'Reunion', 'Russian Federation', 'Saint Barthelemy', 'Saint Martin', 'St. Martin', 'Taipei and environs', 'The Bahamas', 'The Gambia', 'UK', 'Vatican City', 'Viet Nam', 'occupied Palestinian territory', 'Taiwan*', 'Malawi', 'South Sudan', 'Western Sahara', 'Namibia'])

In [36]:
def func(row) :
    if row ["Country_Region"] in json_data :
        row ["Country_Region"] = json_data[row ["Country_Region"]]

    return row

In [37]:
doc = doc.apply(func, axis=1)
doc.head()

  Province_State Country_Region  Confirmed
0          Anhui          China          1
1        Beijing          China         14
2      Chongqing          China          6
3         Fujian          China          1
5      Guangdong          China         26

'01-22-2020'

In [45]:
data = "01-22-2020"

date_column = data.split(".")[0].lstrip("0").replace("-", "/")
date_column

'1/22/2020'

In [47]:
doc.columns

Index(['Province_State', 'Country_Region', 'Confirmed'], dtype='object')

In [48]:
doc.columns = ["Province_State", "Country_Region", date_column]
doc.columns

Index(['Province_State', 'Country_Region', '1/22/2020'], dtype='object')

In [50]:
doc.head()

  Province_State Country_Region  1/22/2020
0          Anhui          China          1
1        Beijing          China         14
2      Chongqing          China          6
3         Fujian          China          1
5      Guangdong          China         26